spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/microservices-with-java-spring-docker-kubernetes?createDatabaseIfNotExist=true
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 4040
